-- IEC-102 E 文件接收系统数据库模式
-- 兼容 OpenGauss/PostgreSQL

-- 创建主表用于跟踪已接收的 E 文件
CREATE TABLE IF NOT EXISTS RECEIVED_EFILES (
    Id SERIAL PRIMARY KEY,
    CommonAddr VARCHAR(100) NOT NULL,
    TypeId VARCHAR(50) NOT NULL,
    FileName VARCHAR(100) NOT NULL,
    ReceivedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FileSize INTEGER NOT NULL,
    Status VARCHAR(20) NOT NULL DEFAULT 'SUCCESS',
    ErrorMessage VARCHAR(500),
    CONSTRAINT uk_efile UNIQUE (CommonAddr, TypeId, FileName)
);

CREATE INDEX idx_received_at ON RECEIVED_EFILES(ReceivedAt);
CREATE INDEX idx_status ON RECEIVED_EFILES(Status);

-- 示例 INFO 表（用于演示）
-- 这些表是根据 E 文件内容创建的
-- 以下是 *_INFO 表的示例模式

CREATE TABLE IF NOT EXISTS STATION_INFO (
    ID VARCHAR(50) PRIMARY KEY,
    Name VARCHAR(100),
    Location VARCHAR(200),
    Latitude DECIMAL(10, 6),
    Longitude DECIMAL(10, 6),
    Capacity DECIMAL(10, 2),
    Status VARCHAR(20),
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DEVICE_INFO (
    ID VARCHAR(50) PRIMARY KEY,
    StationId VARCHAR(50),
    DeviceType VARCHAR(50),
    Model VARCHAR(100),
    Manufacturer VARCHAR(100),
    InstallDate DATE,
    Status VARCHAR(20),
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 示例数据表（用于非 INFO 表，批量插入）
CREATE TABLE IF NOT EXISTS ENERGY_DATA (
    ID SERIAL PRIMARY KEY,
    StationId VARCHAR(50),
    Timestamp TIMESTAMP,
    ActivePower DECIMAL(10, 2),
    ReactivePower DECIMAL(10, 2),
    Voltage DECIMAL(10, 2),
    Current DECIMAL(10, 2),
    Frequency DECIMAL(5, 2),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_energy_station ON ENERGY_DATA(StationId);
CREATE INDEX idx_energy_timestamp ON ENERGY_DATA(Timestamp);

-- 表注释
COMMENT ON TABLE RECEIVED_EFILES IS '跟踪所有已接收和处理的 E 文件';
COMMENT ON COLUMN RECEIVED_EFILES.Id IS '主键标识';
COMMENT ON COLUMN RECEIVED_EFILES.CommonAddr IS '公共地址';
COMMENT ON COLUMN RECEIVED_EFILES.TypeId IS '类型标识';
COMMENT ON COLUMN RECEIVED_EFILES.FileName IS '文件名';
COMMENT ON COLUMN RECEIVED_EFILES.ReceivedAt IS '接收时间';
COMMENT ON COLUMN RECEIVED_EFILES.FileSize IS '文件大小（字节）';
COMMENT ON COLUMN RECEIVED_EFILES.Status IS '处理状态（SUCCESS/ERROR）';
COMMENT ON COLUMN RECEIVED_EFILES.ErrorMessage IS '错误消息';

COMMENT ON TABLE STATION_INFO IS '站点信息表，支持按 ID 进行 UPSERT';
COMMENT ON COLUMN STATION_INFO.ID IS '站点唯一标识';
COMMENT ON COLUMN STATION_INFO.Name IS '站点名称';
COMMENT ON COLUMN STATION_INFO.Location IS '站点位置';
COMMENT ON COLUMN STATION_INFO.Latitude IS '纬度';
COMMENT ON COLUMN STATION_INFO.Longitude IS '经度';
COMMENT ON COLUMN STATION_INFO.Capacity IS '容量';
COMMENT ON COLUMN STATION_INFO.Status IS '状态';
COMMENT ON COLUMN STATION_INFO.UpdatedAt IS '更新时间';

COMMENT ON TABLE DEVICE_INFO IS '设备信息表，支持按 ID 进行 UPSERT';
COMMENT ON COLUMN DEVICE_INFO.ID IS '设备唯一标识';
COMMENT ON COLUMN DEVICE_INFO.StationId IS '所属站点 ID';
COMMENT ON COLUMN DEVICE_INFO.DeviceType IS '设备类型';
COMMENT ON COLUMN DEVICE_INFO.Model IS '设备型号';
COMMENT ON COLUMN DEVICE_INFO.Manufacturer IS '制造商';
COMMENT ON COLUMN DEVICE_INFO.InstallDate IS '安装日期';
COMMENT ON COLUMN DEVICE_INFO.Status IS '设备状态';
COMMENT ON COLUMN DEVICE_INFO.UpdatedAt IS '更新时间';

COMMENT ON TABLE ENERGY_DATA IS '能量测量数据表，仅支持批量插入';
COMMENT ON COLUMN ENERGY_DATA.ID IS '主键标识';
COMMENT ON COLUMN ENERGY_DATA.StationId IS '站点 ID';
COMMENT ON COLUMN ENERGY_DATA.Timestamp IS '测量时间戳';
COMMENT ON COLUMN ENERGY_DATA.ActivePower IS '有功功率';
COMMENT ON COLUMN ENERGY_DATA.ReactivePower IS '无功功率';
COMMENT ON COLUMN ENERGY_DATA.Voltage IS '电压';
COMMENT ON COLUMN ENERGY_DATA.Current IS '电流';
COMMENT ON COLUMN ENERGY_DATA.Frequency IS '频率';
COMMENT ON COLUMN ENERGY_DATA.CreatedAt IS '记录创建时间';
